logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                                            # 'both', 'apk' or 'module'
excluded-patches = "custom-branding-icon-revancify-blue custom-branding-youtube-name"          # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "add-splash-animation materialyou"                                          # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                                               # 'auto', 'latest', 'beta' or a custom one like '17.45.36'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
build-mode = "both"
excluded-patches = "custom-branding-music-name custom-branding-icon-revancify-blue"
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"                                                                        # both arm64-v8a and arm-v7a

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
