# See https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations
compression-level = 9 # compression level for module zips. between 1 and 9
logging-to-file = true # enables logging of every patch process to a seperate file
enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 3 # max number of concurrent building jobs
build-mindetach-module = true
# extended
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"

[YouTube]
build-mode = "both"
excluded-patches = "custom-branding-icon-afn-red custom-branding-name"
included-patches = "materialyou force-premium-heading"
version = "latest"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music-arm64]
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-afn-red"
included-patches = ""
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Music-arm]
build-mode = "both"
app-name = "Music"
excluded-patches = "custom-branding-music-afn-red"
included-patches = ""
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm-v7a"
